#!/bin/bash
# Quick reference for all test commands
# Usage: source this file or copy commands

echo "========================================="
echo "RDCS Test Commands Quick Reference"
echo "========================================="
echo ""

echo "=== Phase 3: ICE & DataChannel Tests ==="
echo ""
echo "# ICE P2P Connection Test"
echo "RUST_LOG=info cargo run -p rdcs-connection --example ice_p2p_test"
echo ""
echo "# DataChannel Video Test"
echo "RUST_LOG=info cargo run -p rdcs-connection --example video_datachannel_test"
echo ""
echo "# End-to-End Video Streaming (Software Encoder)"
echo "RUST_LOG=info cargo run -p rdcs-connection --example video_e2e_test --features software-encoder"
echo ""

echo "=== Phase 4.1: Hardware Encoder Tests ==="
echo ""
echo "# Hardware Encoder Performance Test (VideoToolbox)"
echo "RUST_LOG=info cargo run -p rdcs-connection --example hardware_encoder_test"
echo ""
echo "# Software Encoder Performance Test (OpenH264 baseline)"
echo "RUST_LOG=info cargo run -p rdcs-connection --example hardware_encoder_test --features software-encoder"
echo ""
echo "# Automated Hardware vs Software Comparison"
echo "./test_hardware_encoder.sh"
echo ""

echo "=== Build & Test ==="
echo ""
echo "# Build all libraries"
echo "cargo build --workspace"
echo ""
echo "# Build specific example"
echo "cargo build -p rdcs-connection --example video_e2e_test"
echo ""
echo "# Run all tests"
echo "cargo test --workspace"
echo ""
echo "# Clippy check"
echo "cargo clippy --all-targets --all-features"
echo ""

echo "=== Quick Build Check ==="
echo ""
echo "./check_build.sh"
echo ""

echo "========================================="
