#!/bin/bash
# ICE 跨网络连接测试指南

echo "========================================"
echo "🌐 ICE 跨网络连接测试"
echo "========================================"
echo ""
echo "此测试用于验证 ICE 在不同网络环境下的连接能力"
echo ""
echo "测试场景："
echo "  1. 同一局域网 (已通过 ice_p2p_test 验证)"
echo "  2. 不同局域网 (通过 STUN 穿透)"
echo "  3. 移动热点 vs WiFi"
echo ""
echo "========================================"
echo "📋 测试步骤"
echo "========================================"
echo ""
echo "需要两台机器或一台机器 + 手机热点"
echo ""
echo "【机器 A - Server】"
echo "  1. 编译项目："
echo "     cd /path/to/rdcs"
echo "     cargo build -p rdcs-connection --example ice_server"
echo ""
echo "  2. 运行 server："
echo "     cargo run -p rdcs-connection --example ice_server"
echo ""
echo "  3. 复制输出的 OFFER JSON"
echo ""
echo "  4. 等待接收 ANSWER JSON"
echo "     粘贴 Answer，然后按 Ctrl+D (Mac/Linux) 或 Ctrl+Z Enter (Windows)"
echo ""
echo "【机器 B - Client】"
echo "  1. 编译项目："
echo "     cd /path/to/rdcs"
echo "     cargo build -p rdcs-connection --example ice_client"
echo ""
echo "  2. 运行 client："
echo "     cargo run -p rdcs-connection --example ice_client"
echo ""
echo "  3. 粘贴机器 A 的 OFFER JSON"
echo "     按 Ctrl+D (Mac/Linux) 或 Ctrl+Z Enter (Windows)"
echo ""
echo "  4. 复制输出的 ANSWER JSON"
echo ""
echo "  5. 将 Answer 发送给机器 A"
echo ""
echo "【验证连接】"
echo "  - 两端都应显示: ✅ ICE CONNECTION ESTABLISHED!"
echo "  - 记录连接建立时间"
echo "  - 记录使用的候选类型 (Host/Srflx)"
echo ""
echo "========================================"
echo "🔍 故障排查"
echo "========================================"
echo ""
echo "如果连接失败："
echo "  1. 检查防火墙设置 (允许 UDP 流量)"
echo "  2. 检查 STUN 服务器可达性"
echo "     ping stun.l.google.com"
echo "  3. 使用 DEBUG 日志查看详细信息"
echo "     RUST_LOG=debug cargo run ..."
echo "  4. 检查 NAT 类型"
echo "     cargo run -p rdcs-nat-test"
echo ""
echo "========================================"
echo "📊 记录测试结果"
echo "========================================"
echo ""
echo "请记录以下信息："
echo "  - 网络环境 (同局域网/不同局域网/移动热点)"
echo "  - 连接建立时间"
echo "  - 使用的候选类型"
echo "  - NAT 类型 (如果已知)"
echo "  - 是否成功建立连接"
echo "  - 任何错误信息"
echo ""
echo "将结果更新到："
echo "  docs/testing/PHASE3_NETWORK_TEST_RESULTS.md"
echo ""
echo "========================================"
