// Copyright 2026 RDCS Contributors
// SPDX-License-Identifier: Apache-2.0
//
// Live TWO-CLIENT integration test — simulates the full invite→connect flow
// that two physical devices would perform during 联调, but drives both peers
// from a single test process against the live signaling server.
//
// Flow verified:
//   1. Device A (controlled)  registers, generates an invite code.
//   2. Device B (controller)  registers, sends `use_invite` with that code.
//   3. Server consumes the invite and forwards a `connect_request` to A,
//      carrying the server-minted session_id.
//   4. Device A receives the forwarded `connect_request` on its invitations
//      stream — proving snake_case round-trips in BOTH directions AND that
//      the server routes messages between two real client connections.
//   5. Device A accepts; the `connect_response` routes back to controller B
//      on the SAME session_id — closing the signaling handshake end-to-end.
//
// Run:
//   RDCS_SIGNALING_URL=ws://192.168.31.50:8443/ws \
//     flutter test test/integration/live_two_client_invite_test.dart


import 'package:flutter_test/flutter_test.dart';
import 'package:rdcs_client/core/signaling/models/signaling_message.dart';
import 'package:rdcs_client/core/signaling/signaling_service.dart';
import 'package:rdcs_client/core/signaling/websocket_client.dart';

void main() {
  const serverUrl = String.fromEnvironment(
    'RDCS_SIGNALING_URL',
    defaultValue: 'ws://192.168.31.50:8443/ws',
  );

  group('Live two-client invite → connect_request flow', () {
    late SignalingService deviceA; // controlled / invite generator
    late SignalingService deviceB; // controller / invite user

    setUp(() {
      // Distinct device codes (not shared with other live tests) so the suite
      // is order-independent — reusing a code the server still holds open from
      // a prior test causes a registration collision.
      deviceA = SignalingService(
        serverUrl: serverUrl,
        deviceCode: '200000001',
        platform: 'macos-controlled',
      );
      deviceB = SignalingService(
        serverUrl: serverUrl,
        deviceCode: '200000002',
        platform: 'macos-controller',
      );
    });

    tearDown(() {
      deviceA.disconnect();
      deviceB.disconnect();
    });

    test('invite generated by A and used by B forwards connect_request to A',
        () async {
      // -- Device A comes online and generates an invite ---------------------
      await deviceA.connect();
      expect(deviceA.currentConnectionState, WsConnectionState.connected);

      final invitationFuture =
          deviceA.invitations.first.timeout(const Duration(seconds: 10));

      final inviteCodeFuture =
          deviceA.inviteGenerated.first.timeout(const Duration(seconds: 8));
      deviceA.generateInviteCode();
      final inviteCode = await inviteCodeFuture;
      expect(inviteCode, isNotEmpty);
      // ignore: avoid_print
      print('Device A generated invite: $inviteCode');

      // -- Device B comes online and consumes the invite ---------------------
      await deviceB.connect();
      expect(deviceB.currentConnectionState, WsConnectionState.connected);

      // Watch for any protocol error surfaced to B.
      ErrorMessage? bError;
      final bErrSub = deviceB.errors.listen((e) => bError = e);

      deviceB.useInviteCode(inviteCode);

      // -- Device A must receive the forwarded connect_request ---------------
      final ConnectRequestMessage invite = await invitationFuture;
      await bErrSub.cancel();

      expect(bError, isNull,
          reason: 'server rejected use_invite: '
              '${bError?.code} ${bError?.message}');
      expect(invite.fromCode, deviceB.deviceCode,
          reason: 'connect_request should originate from device B');
      expect(invite.toCode, deviceA.deviceCode,
          reason: 'connect_request should be addressed to device A');
      expect(invite.sessionId, isNotNull,
          reason: 'server-minted session_id must ride on the connect_request');

      // ignore: avoid_print
      print('✅ Device A received connect_request from ${invite.fromCode} '
          '(session ${invite.sessionId})');

      // -- Device A accepts; the connect_response must reach controller B ----
      // B is the initiator, so it receives the response with fromCode == A.
      final responseFuture = deviceB.connectResponses
          .firstWhere((r) => r.fromCode == deviceA.deviceCode)
          .timeout(const Duration(seconds: 10));

      deviceA.respondToConnection(
        sessionId: invite.sessionId!,
        fromCode: deviceA.deviceCode,
        accepted: true,
      );

      final ConnectResponseMessage response = await responseFuture;
      expect(response.accepted, isTrue,
          reason: 'A accepted, so B must see accepted: true');
      expect(response.sessionId, invite.sessionId,
          reason: 'the handshake must close on the SAME server-minted '
              'session_id in both directions');

      // ignore: avoid_print
      print('✅ Device B received connect_response (accepted, '
          'session ${response.sessionId}) → full handshake closed end-to-end');
    });
  }, skip: serverUrl.isEmpty ? 'RDCS_SIGNALING_URL not set' : false);
}
